spring.application.name=proyecto

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=guardado_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=appuser
spring.datasource.password=67
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect